plugins {
    id 'com.android.application'
}

android {
    namespace 'com.empire.game'
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId 'com.empire.game'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'

    externalNativeBuild {
        cmake {
            cppFlags ''
        }
    }
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}

dependencies {
}
