package defpackage;

/* JADX INFO: compiled from: r8-map-id-6c0b98a496b39c94623be7f94db3802dc9fd57238d8c9cafbc19343a9e5954ee */
/* JADX INFO: loaded from: /data/data/com.termux/files/home/EMPIRE/samp-client-src/classes.dex */
public abstract class ay {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = s32.x;
        a = j2;
        b = s32.e;
        c = s32.g;
        d = s32.v;
        long j3 = s32.I;
        e = j3;
        f = s32.m;
        long j4 = s32.i;
        g = j4;
        h = s32.b;
        i = s32.a;
        j = s32.E;
        long j5 = s32.D;
        k = j5;
        l = j5;
        m = s32.G;
        n = s32.L;
        long j6 = s32.K;
        o = j6;
        p = j6;
        q = s32.N;
        r = j4;
        s = s32.y;
        t = s32.S;
        long j7 = s32.R;
        u = j7;
        v = j7;
        w = s32.U;
        x = s32.z;
        y = s32.B;
        z = s32.H;
        long j8 = s32.J;
        A = j8;
        B = j8;
        C = j3;
        D = s32.h;
        E = s32.O;
        long j9 = s32.Q;
        F = j9;
        G = j9;
        H = s32.P;
        I = j2;
        J = j2;
        K = s32.u;
        L = s32.t;
        M = s32.s;
        N = s32.w;
        O = s32.j;
        P = s32.r;
        Q = s32.C;
        R = s32.V;
        long j10 = s32.X;
        S = j10;
        T = j10;
        U = s32.W;
    }
}
