package defpackage;

/* JADX INFO: compiled from: r8-map-id-6c0b98a496b39c94623be7f94db3802dc9fd57238d8c9cafbc19343a9e5954ee */
/* JADX INFO: loaded from: /data/data/com.termux/files/home/EMPIRE/samp-client-src/classes.dex */
public abstract class dl3 {
    public static final long A;
    public static final long A0;
    public static final zv0 A1;
    public static final long B;
    public static final xq0 B0;
    public static final long B1;
    public static final long C;
    public static final zv0 C0;
    public static final long C1;
    public static final xq0 D;
    public static final long D0;
    public static final long D1;
    public static final zv0 E;
    public static final long E0;
    public static final xq0 E1;
    public static final long F;
    public static final long F0;
    public static final zv0 F1;
    public static final long G;
    public static final xq0 G0;
    public static final long G1;
    public static final long H;
    public static final zv0 H0;
    public static final long H1;
    public static final xq0 I;
    public static final long I0;
    public static final long I1;
    public static final zv0 J;
    public static final long J0;
    public static final xq0 J1;
    public static final long K;
    public static final long K0;
    public static final zv0 K1;
    public static final long L;
    public static final xq0 L0;
    public static final long L1;
    public static final long M;
    public static final zv0 M0;
    public static final long M1;
    public static final xq0 N;
    public static final long N0;
    public static final long N1;
    public static final zv0 O;
    public static final long O0;
    public static final xq0 O1;
    public static final long P;
    public static final long P0;
    public static final zv0 P1;
    public static final long Q;
    public static final xq0 Q0;
    public static final long Q1;
    public static final long R;
    public static final zv0 R0;
    public static final long R1;
    public static final xq0 S;
    public static final long S0;
    public static final long S1;
    public static final zv0 T;
    public static final long T0;
    public static final xq0 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final xq0 V0;
    public static final long W;
    public static final zv0 W0;
    public static final xq0 X;
    public static final long X0;
    public static final zv0 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final zv0 a;
    public static final long a0;
    public static final xq0 a1;
    public static final long b;
    public static final long b0;
    public static final zv0 b1;
    public static final long c;
    public static final xq0 c0;
    public static final long c1;
    public static final long d;
    public static final zv0 d0;
    public static final long d1;
    public static final xq0 e;
    public static final long e0;
    public static final long e1;
    public static final zv0 f;
    public static final long f0;
    public static final xq0 f1;
    public static final long g;
    public static final long g0;
    public static final zv0 g1;
    public static final long h;
    public static final xq0 h0;
    public static final long h1;
    public static final long i;
    public static final zv0 i0;
    public static final long i1;
    public static final xq0 j;
    public static final long j0;
    public static final long j1;
    public static final zv0 k;
    public static final long k0;
    public static final xq0 k1;
    public static final long l;
    public static final long l0;
    public static final zv0 l1;
    public static final long m;
    public static final xq0 m0;
    public static final long m1;
    public static final long n;
    public static final zv0 n0;
    public static final long n1;
    public static final xq0 o;
    public static final long o0;
    public static final long o1;
    public static final zv0 p;
    public static final long p0;
    public static final xq0 p1;
    public static final long q;
    public static final long q0;
    public static final zv0 q1;
    public static final long r;
    public static final xq0 r0;
    public static final long r1;
    public static final long s;
    public static final zv0 s0;
    public static final long s1;
    public static final xq0 t;
    public static final long t0;
    public static final long t1;
    public static final zv0 u;
    public static final long u0;
    public static final xq0 u1;
    public static final long v;
    public static final long v0;
    public static final zv0 v1;
    public static final long w;
    public static final xq0 w0;
    public static final long w1;
    public static final long x;
    public static final zv0 x0;
    public static final long x1;
    public static final xq0 y;
    public static final long y0;
    public static final long y1;
    public static final zv0 z;
    public static final long z0;
    public static final xq0 z1;

    static {
        xq0 xq0Var = nl3.a;
        zv0 zv0Var = zb3.b;
        a = zv0Var;
        b = oz2.v(24.0d);
        c = oz2.w(16);
        d = oz2.v(0.5d);
        xq0 xq0Var2 = nl3.c;
        e = xq0Var2;
        f = zv0Var;
        g = oz2.v(20.0d);
        h = oz2.w(14);
        i = oz2.v(0.2d);
        j = xq0Var2;
        k = zv0Var;
        l = oz2.v(16.0d);
        m = oz2.w(12);
        n = oz2.v(0.4d);
        o = xq0Var2;
        p = zv0Var;
        q = oz2.v(64.0d);
        r = oz2.w(57);
        long jV = oz2.v(0.2d);
        kh3[] kh3VarArr = jh3.b;
        long j2 = jV & 1095216660480L;
        if (j2 == 0) {
            o21.a("Cannot perform operation for Unspecified type.");
        }
        s = oz2.D(-jh3.c(jV), j2);
        t = xq0Var2;
        u = zv0Var;
        v = oz2.v(52.0d);
        w = oz2.w(45);
        x = oz2.v(0.0d);
        y = xq0Var2;
        z = zv0Var;
        A = oz2.v(44.0d);
        B = oz2.w(36);
        C = oz2.v(0.0d);
        D = xq0Var2;
        E = zv0Var;
        F = oz2.v(40.0d);
        G = oz2.w(32);
        H = oz2.v(0.0d);
        I = xq0Var2;
        J = zv0Var;
        K = oz2.v(36.0d);
        L = oz2.w(28);
        M = oz2.v(0.0d);
        N = xq0Var2;
        O = zv0Var;
        P = oz2.v(32.0d);
        Q = oz2.w(24);
        R = oz2.v(0.0d);
        S = xq0Var2;
        T = zv0Var;
        U = oz2.v(20.0d);
        V = oz2.w(14);
        W = oz2.v(0.1d);
        xq0 xq0Var3 = nl3.b;
        X = xq0Var3;
        Y = zv0Var;
        Z = oz2.v(16.0d);
        a0 = oz2.w(12);
        b0 = oz2.v(0.5d);
        c0 = xq0Var3;
        d0 = zv0Var;
        e0 = oz2.v(16.0d);
        f0 = oz2.w(11);
        g0 = oz2.v(0.5d);
        h0 = xq0Var3;
        i0 = zv0Var;
        j0 = oz2.v(28.0d);
        k0 = oz2.w(22);
        l0 = oz2.v(0.0d);
        m0 = xq0Var2;
        n0 = zv0Var;
        o0 = oz2.v(24.0d);
        p0 = oz2.w(16);
        q0 = oz2.v(0.2d);
        r0 = xq0Var3;
        s0 = zv0Var;
        t0 = oz2.v(20.0d);
        u0 = oz2.w(14);
        v0 = oz2.v(0.1d);
        w0 = xq0Var3;
        x0 = zv0Var;
        y0 = oz2.v(24.0d);
        z0 = oz2.w(16);
        A0 = oz2.v(0.15d);
        B0 = xq0Var3;
        C0 = zv0Var;
        D0 = oz2.v(20.0d);
        E0 = oz2.w(14);
        F0 = oz2.v(0.25d);
        G0 = xq0Var3;
        H0 = zv0Var;
        I0 = oz2.v(16.0d);
        J0 = oz2.w(12);
        K0 = oz2.v(0.4d);
        L0 = xq0Var3;
        M0 = zv0Var;
        N0 = oz2.v(64.0d);
        O0 = oz2.w(57);
        P0 = oz2.w(0);
        Q0 = xq0Var3;
        R0 = zv0Var;
        S0 = oz2.v(52.0d);
        T0 = oz2.w(45);
        U0 = oz2.w(0);
        V0 = xq0Var3;
        W0 = zv0Var;
        X0 = oz2.v(44.0d);
        Y0 = oz2.w(36);
        Z0 = oz2.w(0);
        a1 = xq0Var3;
        b1 = zv0Var;
        c1 = oz2.v(40.0d);
        d1 = oz2.w(32);
        e1 = oz2.w(0);
        f1 = xq0Var3;
        g1 = zv0Var;
        h1 = oz2.v(36.0d);
        i1 = oz2.w(28);
        j1 = oz2.w(0);
        k1 = xq0Var3;
        l1 = zv0Var;
        m1 = oz2.v(32.0d);
        n1 = oz2.w(24);
        o1 = oz2.w(0);
        p1 = xq0Var3;
        q1 = zv0Var;
        r1 = oz2.v(20.0d);
        s1 = oz2.w(14);
        t1 = oz2.v(0.1d);
        xq0 xq0Var4 = nl3.a;
        u1 = xq0Var4;
        v1 = zv0Var;
        w1 = oz2.v(16.0d);
        x1 = oz2.w(12);
        y1 = oz2.v(0.5d);
        z1 = xq0Var4;
        A1 = zv0Var;
        B1 = oz2.v(16.0d);
        C1 = oz2.w(11);
        D1 = oz2.v(0.5d);
        E1 = xq0Var4;
        F1 = zv0Var;
        G1 = oz2.v(28.0d);
        H1 = oz2.w(22);
        I1 = oz2.w(0);
        J1 = xq0Var3;
        K1 = zv0Var;
        L1 = oz2.v(24.0d);
        M1 = oz2.w(16);
        N1 = oz2.v(0.15d);
        O1 = xq0Var4;
        P1 = zv0Var;
        Q1 = oz2.v(20.0d);
        R1 = oz2.w(14);
        S1 = oz2.v(0.1d);
        T1 = xq0Var4;
    }
}
