package defpackage;

/* JADX INFO: compiled from: r8-map-id-6c0b98a496b39c94623be7f94db3802dc9fd57238d8c9cafbc19343a9e5954ee */
/* JADX INFO: loaded from: /data/data/com.termux/files/home/EMPIRE/samp-client-src/classes.dex */
public abstract class xx {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = s32.q;
        a = j2;
        b = s32.f;
        c = s32.d;
        d = s32.m;
        e = s32.H;
        long j3 = s32.s;
        f = j3;
        g = j3;
        h = s32.c;
        i = s32.g;
        j = s32.F;
        long j4 = s32.J;
        k = j4;
        l = s32.D;
        long j5 = s32.G;
        m = j5;
        n = s32.M;
        long j6 = s32.Q;
        o = j6;
        p = s32.K;
        long j7 = s32.N;
        q = j7;
        r = j3;
        s = s32.B;
        t = s32.T;
        long j8 = s32.X;
        u = j8;
        v = s32.R;
        long j9 = s32.U;
        w = j9;
        x = s32.A;
        long j10 = s32.y;
        y = j10;
        long j11 = s32.I;
        z = j11;
        A = j5;
        B = j4;
        C = j11;
        D = s32.h;
        long j12 = s32.P;
        E = j12;
        F = j7;
        G = j6;
        H = j12;
        I = j2;
        J = s32.o;
        K = s32.k;
        L = s32.l;
        M = s32.n;
        N = s32.i;
        O = s32.p;
        P = j2;
        Q = j10;
        long j13 = s32.W;
        R = j13;
        S = j9;
        T = j8;
        U = j13;
    }
}
